= Link Verifier image:https://travis-ci.org/bmuschko/link-verifier.svg?branch=master["Build Status", link="https://travis-ci.org/bmuschko/link-verifier"] image:https://goreportcard.com/badge/github.com/bmuschko/link-verifier["Go Report Card", link="https://goreportcard.com/report/github.com/bmuschko/link-verifier"] image:https://codecov.io/gh/bmuschko/link-verifier/branch/master/graph/badge.svg["Codecov", link="https://codecov.io/gh/bmuschko/link-verifier"]

A tool for verifying links in text-based files. Written in Go, runnable as executable.

== Motivation

Ambitious tech writers use plain-text mark-up formats like link:http://asciidoc.org/[AsciiDoc] and
link:https://daringfireball.net/projects/markdown/[Markdown] for turning text into properly formatted blog posts, web
pages and documentation. Incorporating URLs to refer to external resources is part of the process. Before publishing
content it's important if the linked URLs are valid and can be resolved. Nothing feels more unprofessional than broken
links in a carefully crafted document.

Link verifier to the rescue! Automatically discover all mark-up files in a given directory and verify all links
found in the documents before publishing them.

== Installation

=== Prebuilt libraries

link:https://github.com/bmuschko/link-verifier/releases[Prebuilt libraries for various platforms] are available on GitHub.
Just download, exact the archive and execute the binary.

=== Building from source

Building from source requires that you have link:https://golang.org/doc/install[Go] installed on your machine.

``` shell
go get -u -v github.com/bmuschko/link-verifier
```

Run the program with `link-verifier` from anywhere in the file system.

== Command line options

- `sourceDir`: The source directory used to search for mark-up files. Defaults to the directory `content`.
- `fail`: Fails the program if at least one discovered link cannot be resolved. Default to `true`.

== Usage on CI

Integrating the tool with a build on CI is a breeze and can used as validation step before publishing AsciiDoc files.

=== Travis CI

The following `.travis.yml` demonstrate the use of the prebuilt binary version on Linux 64 bit:

``` shell
before_script:
  - wget https://github.com/bmuschko/link-verifier/releases/download/v0.1/link-verifier-0.1-linux64.tar.gz -O /tmp/link-verifier.tar.gz
  - tar -xvf /tmp/link-verifier.tar.gz
  - export PATH=$PATH:$PWD/link-verifier/

script:
  - ./link-verifier
```

== Contribute!

It's easy to contribute to this project. Install link:https://golang.org/doc/install[Go] and the package manager
link:https://glide.sh/[Glide]. Then run the following commands to get the source code, resolve external dependencies
and build the project.

``` shell
git clone https://github.com/bmuschko/link-verifier.git
cd link-verifier
glide install
go build
```



